#"path_in": "s3://kitchen-mgh-data/Projects/TestData/RNAseq/Fastq"
#"path_out": "s3://kitchen-mgh-data/Projects/TestData/RNAseq/Processed"
"path_in": "/Users/rk504/WORK/exceRpt/exceRpt_github/ExampleData"
"path_out": "/Users/rk504/WORK/exceRpt/exceRpt_github/TESTING/output"
"sample_table": "/Users/rk504/WORK/exceRpt/exceRpt_github/TESTING/sampleTable.csv"
"path_annotation": "~/Dropbox_MGH/Annotations/Human"
"path_bin": "/efs/bin/exceRpt_dependencies"
"path_exceRpt": "/efs/Pipelines/exceRpt/"
"path_tmp": "/tmp/RNAseq"
"rapid_run": "True"
"data_source": "file"
#
## Alignment Params:
"minInsertSize": "18"
"star_outFilterMatchNminOverLread": "0.9"
"star_outFilterMismatchNmax": "1"
"star_outFilterMismatchNoverLmax": "0.3"
"star_outFilterScoreMinOverLread": "0.5"
"star_alignEndsType": "Local"
